languague: php
php:
 - 8.0
env:
  - DB=mysql
  
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "INSERT INTO `tbl_usuarios`(`id`, `nombre`, `direccion`, `ciudad`, `telefono`, `correo`, `password`) VALUES (2,'usuario de prueba','calle 8','Bogota',00000,'prueba@prueba.com','123456')" -uroot; fi

notifications: 
 email: eli.13.07@hotmail.com
